# Sample .travis.yml for R projects
language: r
cache: packages
sudo: required

warnings_are_errors: false
notifications:
  on_success: always
  on_failure: always

after_success:  
  - bash <(curl -s https://codecov.io/bash)