# Sample .travis.yml for R projects
language: r
cache: packages
sudo: required

##
# code to get gdal working #
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - r-cran-rjava
      - libv8-dev 
      - libmagick++-dev
      
r_binary_packages:
 - rgdal
###

r_packages:
  - covr
  - raster

after_success:
  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false
notifications:
  on_success: always
  on_failure: always