# Sample .travis.yml for R projects
language: r
cache: packages
sudo: required

after_success:
  - bash <(curl -s https://codecov.io/bash)

warnings_are_errors: false
notifications:
  on_success: change
  on_failure: change
