# Sample .travis.yml for R projects
language: r
cache: packages
sudo: required

r_github_packages:
  - jimhester/covr

after_success:
  - bash <(curl -s https://codecov.io/bash)

#after_success:
#  - Rscript -e 'library(covr);codecov()'

warnings_are_errors: false
notifications:
  on_success: change
  on_failure: change
